run:
  timeout: 5m
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - intrange
    - misspell
    - noctx
    - staticcheck
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
